### ISSUE TITLE
Check inherited members for `__init__` when merging docstrings

### ISSUE THREAD

**Issue by pawamoy** [mkdocstrings/python#106]
**Is your feature request related to a problem? Please describe.**
Currently the Python handler only checks in declared members for an `__init__` method when merging docstrings together. That means it won't show the docstring of an inherited `__init__`.

**Describe the solution you'd like**
Also check inherited members.

**Describe alternatives you've considered**
/

**Additional context**
https://github.com/mkdocstrings/griffe/issues/205

**Comment by waylan** [comment]
As example of this issue is provided in [this comment](https://github.com/Python-Markdown/markdown/pull/1379#issuecomment-1735567245).
