### ISSUE TITLE
Conda wrong dependencies 

### ISSUE THREAD

**Issue by motybz** [mkdocstrings/python#11]
**Describe the bug**
When installing **one** of the following packages:
- mkdocstrings
- mkdocstrings-python
- mkdocstrings-python-legacy
**All** of those packages were installed (due to a wrong dependency definition I guess...)
This behavior does not allow working with the legacy version...

**To Reproduce**
conda install mkdocstrings-python-legacy

**System (please complete the following information):**
- mkdocstrings-python-legacy: 0.2.2
- Python version: 3.7
- OS: Linux

**Comment by pawamoy** [comment]
Thanks for the report!

mkdocstrings definitely does not depend on mkdocstrings-python: https://github.com/mkdocstrings/mkdocstrings/blob/61c1666de9663cd70a2e46e40083e789bd30cc10/pyproject.toml#L32, so it shouldn't be installed. I'm not taking care of the Conda packages, you'll have to see with @bandersen23 or @hadim I guess :confused:

**Comment by bandersen23** [comment]
Sorry about that! Fixed in above linked PR that will be merged soon. Thanks for the catch!

**Comment by bandersen23** [comment]
Once it's merged, it's installable from `conda-forge` within an hour or two at most.

**Comment by pawamoy** [comment]
Thanks for the extremely quick fix @bandersen23! Closing :slightly_smiling_face:

**Comment by motybz** [comment]
Works like charm, thank you!
