### ISSUE TITLE
Class methods' full source path is shown instead of the identifier used for it

### ISSUE THREAD

**Issue by ianspektor** [mkdocstrings/python#111]
**Describe the bug**

Hey! Thank you very much for the work on #90 and #91 :)

91 does seem fixed, but 90 doesn't. Upgraded `mkdocstrings-python` to `1.5.3` and `griffe` to `0.36.8` (see [PR](https://github.com/google/temporian/pull/290)) and I'm still seeing the object's full path (`temporian.implementation.numpy.data.event_set.EventSet.begin`) instead of the identifier I used for it (`::: temporian.EventSet.begin`) in the header (see the rendered doc [here](https://temporian--290.org.readthedocs.build/en/290/reference/temporian/operators/begin/)). Note that I import the `EventSet` class in my root `__init__` which makes the identifier work.

Full explanation in the original issue.

**To Reproduce**
See #90 

**Expected behavior**
See #90

Thanks in advance for any help!

**Comment by pawamoy** [comment]
Hmm, weird, I expose objects from submodules in my root init module too, and they correctly keep their alias path in the docs, for example: https://mkdocstrings.github.io/griffe/reference/griffe/#griffe.Attribute.

I'll check out your repo again :slightly_smiling_face:

**Comment by pawamoy** [comment]
Actually I'm able to replicate. It works fine when I let mkdocstrings unfold members of `griffe` or `griffe.Attribute`, but if I inject `griffe.Attribute.functions` directly, the path is the canonical one.

**Comment by ianspektor** [comment]
Great to hear! Let me know if there's anything you need from my side

**Comment by pawamoy** [comment]
Pushed a fix, will release soon :slightly_smiling_face:
