### ISSUE TITLE
When a class method overrides it's parent class method, and has no docstring, inherit from the parent class method

### ISSUE THREAD

**Issue by asakiasako** [mkdocstrings/python#13]
**Is your feature request related to a problem? Please describe.**
It's better to describe it with an example.
``` python
from abc import abstractmethod, ABC
class Base(ABC):
    @abstractmethod
    def some_method():
        """Docstring...
        Args:
             ......
        """

class Child(Base):
    def some_method():
        # no docstring, expected to inherit from the abstract class.
        do_some_work
```

In the old legacy python handler, when a method that overrides a method from a base class has no docstring, it will inherit doctring from the method of the base class. So I only have to write docstring in the abstract class for a single time.

But in the new python handler, it will not. So I have to copy the same docstring to many of the child classes...

**Describe the solution you'd like**
Try to inherit from parent class if a method has no docstring.

I think a even better solution is, when some keywords write to the docstring, it will inherit docstring from parent class method:

```
class Child(Base):
    def some_method():
        """See base class"""
```

This is what google has suggested in https://google.github.io/styleguide/pyguide.html#383-functions-and-methods :

> A method that overrides a method from a base class may have a simple docstring sending the reader to its overridden method’s docstring, such as """See base class.""". The rationale is that there is no need to repeat in many places documentation that is already present in the base method’s docstring. However, if the overriding method’s behavior is substantially different from the overridden method, or details need to be provided (e.g., documenting additional side effects), a docstring with at least those differences is required on the overriding method.

**Comment by pawamoy** [comment]
Hello, thanks for taking the time to open an issue :slightly_smiling_face: 

Indeed, there's no support for inheritance in Griffe yet, at least not when visiting code instead of inspecting it.

This feature is getting hard to get right.

- should a class inherit a docstring from its parents? sometimes yes sometimes no, depends on the user's wishes
- should a class method inherit a docstring from its parents? maybe:
    - the method was redefined but has no docstring: yes in your case, probably no in other cases
    - the method was not redefined: probably no in most cases, yes in some cases
- same questions for inherited attributes
- must be handled both when visiting and inspecting code:
    - during inspection, members are automatically inherited, and we must know which one are inherited and which one are inherited and redefined
    - during visit, members are not automatically inherited. It must be done in a post-process task (again, not yet implemented), applying the same logic

Ultimately, I think it should be configurable, since there's no way to satisfy everyone.

**Comment by asakiasako** [comment]
Thanks for your explanation. I agree with you that the best way is make it configurable. 

Thanks to the issue link you shared, I can try to make some change by myself for my specific need(^-^)

**Comment by analog-cbarber** [comment]
A related issue is if you don't inherit the doc-string and pull it into the generated docs, it would be nice that cross references to inherited doc-strings still work and dispatched to the parent implementation. As it stands now, you have to figure out the appropriate implementation class manually.

**Comment by pawamoy** [comment]
Good timing @dotpmrcunha, yes, we plan on making this configurable. We recently added static support for inheritance in Griffe, allowing us to work on this feature :slightly_smiling_face:

**Comment by pawamoy** [comment]
I'd like to continue this discussion in the equivalent Griffe issue: https://github.com/mkdocstrings/griffe/issues/96
