### ISSUE TITLE
bug: Pycon syntax not supported even in Examples section?

### ISSUE THREAD

**Issue by MusicalNinjaDad** [mkdocstrings/python#136]
Even within an examples block:

```
    Examples:
    --------
    >>> [x for x in flatten([1,2,[3,4,[5],6],7,[8,9]])]
    [1, 2, 3, 4, 5, 6, 7, 8, 9]
```

is rendered as nested quotes:

![image](https://github.com/mkdocstrings/python/assets/102677655/338a19f9-e124-427c-a775-55bb63f73897)

according to #18, this should work (only) within an examples block

> That's a trade-off we made: `Examples` is parsed as an actual examples section, while `Example` is parsed as an admonition.
> 
> Python interactive session lines outside of actual code blocks (triple backticks) are only parsed as such when in an Examples section. 
> 
_Originally posted by @pawamoy in https://github.com/mkdocstrings/python/issues/18#issuecomment-1100778493_
          
Current workaround to add code block requires an extra blank line for doctest, which renders (less) badly and is error-prone when typing doctrings

```
    Examples:
    --------
    ```
    >>> [x for x in flatten([1,2,[3,4,[5],6],7,[8,9]])]
    [1, 2, 3, 4, 5, 6, 7, 8, 9]

    ```
``` 

![image](https://github.com/mkdocstrings/python/assets/102677655/60b6fa28-b48d-467e-aedf-4494311e5482)

Theme: Material
Versions:
mkdocs                     1.5.3
mkdocs-autorefs            0.5.0
mkdocs-material            9.5.11
mkdocs-material-extensions 1.3.1
mkdocstrings               0.24.0
mkdocstrings-python        1.8.0

**Comment by pawamoy** [comment]
Try this instead:

```
    Examples
    --------
    >>> [x for x in flatten([1,2,[3,4,[5],6],7,[8,9]])]
    [1, 2, 3, 4, 5, 6, 7, 8, 9]
```

(no colon in the section title)

**Comment by MusicalNinjaDad** [comment]
Thanks, I tried that and it still didn't work ...

I've found a workaround by monkeypatching the regex used in doctest to also consider ` ``` ` as signifying the end of a want-block (available from [pypi](https://pypi.org/project/pytest-doctest-mkdocstrings/) via `pip install pytest-doctest-mkdocstrings`) so this is not urgent for me anymore.

**Comment by pawamoy** [comment]
I'm gonna close this but please do provide additional information if you still believe there is a bug in our Numpydoc-style docstring parser :slightly_smiling_face:

**Comment by MusicalNinjaDad** [comment]
Thanks. I think the issue was that I wasn't perfectly following numpy or google conventions - to try and manage between readability in multiple locations (the code, my ide and the docs).
I've decided to leave the docstring monkeypatch in place as using codeblocks improves the rendering in my ide for example
