### ISSUE TITLE
show_category_heading: true and group_by_category: true does not work

### ISSUE THREAD

**Issue by pedrolabonia** [mkdocstrings/python#14]
**Describe the bug**
Using `show_category_heading: true` and `group_by_category: true` does not work.

**To Reproduce**
Enable these settings

**Expected behavior**
Expected to have TOC separate them

**Fix**

The bug seems to happen here
https://github.com/mkdocstrings/python/blob/d5ea1c5cf7884d8c019145f73685a84218e69840/src/mkdocstrings_handlers/python/templates/material/_base/children.html#L16

Removing ``any()`` results in the expected behavior.

Since we're calling `.values()`, if there's no values it already returns `False`.

**Comment by pedrolabonia** [comment]
Proposed fix: https://github.com/pedrolabonia/python/commit/0772ccc5109e89ad1636756fff723182cd878e43

**Comment by pawamoy** [comment]
The point of the `any` filter is actually to filter out objects that have no docstring or an empty docstring. And I realize it's actually insufficient to do it like that.

Let say `show_if_no_docstring` is false, and there's one function with no docstring in `obj.functions.values()`. Without `any` we would render the category header for nothing (the category is empty).

Now if `show_if_no_docstring` is true, we shouldn't filter out with `any`, and just check if there are objects.

I think we need a more powerful function on the handler's side, to do this filtering for us based on the `show_if_no_docstring` option.

**Comment by pedrolabonia** [comment]
Hmm.. I get it. So that function would be in the `handler.py` in this repo? I confess I'm not used to working with jinja and markdown that much so I'm a little green yet and trying to figure out the data flow between mkdocstrings-python and mkdocstrings. If you have any direction I can give it a go.

**Comment by pawamoy** [comment]
Well I wanted to see how it could be done and I ended up implementing the change :sweat_smile: 
I hope you don't mind! Let me know what you think of #16.

**Comment by pawamoy** [comment]
Also, can you confirm that the original issue was that in some cases the category headings were not rendered? It isn't clear in the description.

**Comment by pedrolabonia** [comment]
In my case, I could never get them to render the category headings at all, and could never group the children by category.

**Comment by pawamoy** [comment]
OK I've merged the PR. We'll need to wait for a new release of mkdocstrings before releasing one for the handler. That should'nt take too long.
