### ISSUE TITLE
tests: Write end-to-end tests

### ISSUE THREAD

**Issue by pawamoy** [mkdocstrings/python#150]
With our growing number of rendering options, it is hard to make sure that changes to templates do not cause regressions. We should add end-to-end tests for all combinations of rendering options (matrix), with simple input, asserting the output stays unchanged on next runs. We could maybe use [pytest inline snapshot](https://15r10nk.github.io/inline-snapshot/pytest/) from @15r10nk for that :wink:

**Comment by 15r10nk** [comment]
You can take a look here https://github.com/15r10nk/lazy-imports-lite/blob/main/tests%2Ftest_exec.py where I do end to end tests. Just to get some inspiration.

There are a lot of ways to use inline-snapshot. I'm curious how you will use it.
