### ISSUE TITLE
bug: [Python] Most classes in the module show no members. Really weird bug

### ISSUE THREAD

**Issue by Ark-kun** [mkdocstrings/python#165]
### Description of the bug

I've used mkdosctrings with mkdocs-material and the generated documentation seemed good until I noticed that while some classes show members in the ToC, more than half of the classes do not show any members.

I looked at good and bad classes and I cannot understand the difference. For example, the `class Content` shows nothing (not even `__init__`) while `class ChatSession` and `class Image` show something. Both classes are defined in same module, have no base classes.

Also, I see the some classes have `__init__`, but `ChatSession` does not show `__init__` despite actually having `__init__` and showing other methods like `send_message`.

I've dumped the API using Griffe and everything looks good there. All members are present.
```
griffe dump vertexai -o ../griffe.json
```

Screenshot:
![image](https://github.com/mkdocstrings/mkdocstrings/assets/1829149/1b3bbcab-c33e-4906-8142-f95c76fc60d3)

### To Reproduce
```
pip install google-cloud-aiplatform
```
Contents of `mkdocs.yml`:
```
site_name: My Site

theme:
  name: material

plugins:
- mkdocstrings

nav:
  - "Reference": reference.md
```
Contents of `docs/reference.md`
```
::: vertexai.generative_models
```
```
mkdocs build
```

### Expected behavior
I expect all public members to be shown.

### Environment information

```bash
python -m mkdocstrings.debug  # | xclip -selection clipboard
```
```
- __System__: Windows-10-10.0.19045-SP0
- __Python__: cpython 3.10.2 (C:\Users\User\AppData\Local\Programs\Python\Python310\python.exe)
- __Environment variables__:
- __Installed packages__:
  - `mkdocstrings` v0.25.1
```

#### Snippets from Griffe output:

`Content`
```
              {
                "kind": "class",
                "name": "Content",
                "lineno": 1778,
                "endlineno": 1841,
                "docstring": {
                  "value": ".....",
                  "lineno": 1779,
                  "endlineno": 1787
                },
                "labels": [],
                "members": [
                  {
                    "kind": "function",
                    "name": "__init__",
                    "lineno": 1789,
                    "endlineno": 1796,
                    "labels": [],
                    "members": [],
                    "decorators": [],
                    "parameters": [
                      {
                        "name": "self",
                        "annotation": null,
                        "kind": "positional or keyword",
                        "default": null
                      },
                      {
...
```
`ChatSession`
```
              {
                "kind": "class",
                "name": "ChatSession",
                "lineno": 745,
                "endlineno": 1127,
                "docstring": {
                  "value": "Chat session holds the chat history.",
                  "lineno": 746,
                  "endlineno": 746
                },
                "labels": [],
                "members": [
                  {
                    "kind": "function",
                    "name": "__init__",
                    "lineno": 751,
                    "endlineno": 766,
                    "labels": [],
                    "members": [],
                    "decorators": [],
                    "parameters": [
                      {
                        "name": "self",
                        "annotation": null,
                        "kind": "positional or keyword",
                        "default": null
                      },
```

**Comment by pawamoy** [comment]
Hello, thanks for the report :slightly_smiling_face: 

Your methods don't have docstrings. If you want them to appear in the generated docs, you need to set [`show_if_no_docstring: true`](https://mkdocstrings.github.io/python/usage/configuration/docstrings/#show_if_no_docstring) in mkdocs.yml or under `::: path.to.your.Class`.

**Comment by Ark-kun** [comment]
Thank you a lot. `show_if_no_docstring` has helped.

I guess I missed one of the pages of the configuration sections. I wonder whether having all options available at some page would have helped to avoid my mistake.

**Comment by pawamoy** [comment]
Thanks for coming back and closing :slightly_smiling_face: 

All options are summarized here: https://mkdocstrings.github.io/python/usage/#options-summary.
