### ISSUE TITLE
feature: example code block copy without prompt

### ISSUE THREAD

**Issue by shenxiangzhuang** [mkdocstrings/python#179]
### Is your feature request related to a problem? Please describe.

https://mkdocstrings.github.io/python/usage/configuration/docstrings/?h=example#show_docstring_examples

The example code shows here is:
```
>>> print("hello")
hello
```
When I copy the code by the click button, I copy all the code in it(with `>>> `).

### Describe the solution you'd like

After copy, we get `print("hello")` only, without the prompt `>>>` and the output, just as sklearn docs in [here](https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html#kmeans)

**Comment by pawamoy** [comment]
Hi @shenxiangzhuang, thanks for the request :slightly_smiling_face: We already track it here: https://github.com/mkdocstrings/mkdocstrings/issues/668. Closing!
