### ISSUE TITLE
Interactive Python sessions in docstrings do not create code-blocks

### ISSUE THREAD

**Issue by francois-rozet** [mkdocstrings/python#18]
**Describe the bug**

Interactive Python prompts (`>>>`) in docstrings are parsed as chevrons instead of creating code-blocks.

**Expected behavior**

The prompts should be detected so as to create interactive Python code-blocks. The legacy python handler does.

**Screenshots**

The following text in a docstring leads to an admonition with ill-formated code.

```text
Example:
    >>> x = torch.rand(5, 3, 256, 256)
    >>> l = tv(x)
    >>> l.size()
    torch.Size([5])
```

<img width="596" alt="image" src="https://user-images.githubusercontent.com/37352336/163691887-dfc9fe17-06dd-4266-a512-f4be7bc13e97.png">

**System (please complete the following information):**

- `mkdocstrings-python` version: 0.6.6
- Python version: 3.8.10
- OS: Ubuntu 20.04

**Additional context**

This formatting is very common in Google-style and NumPy-style docstrings and allows to use [doctest](https://docs.python.org/3/library/doctest.html).

**Comment by pawamoy** [comment]
Thanks for the report.

That's a trade-off we made: `Examples` is parsed as an actual examples section, while `Example` is parsed as an admonition.

Python interactive session lines outside of actual code blocks (triple backticks) are only parsed as such when in an Examples section. 

The best thing we could have is a proper Markdown extension that recognizes such pycon blocks and transforms them as actual pycon code blocks. I didn't get the time to play with this idea yet. Not sure how feasible it is.

**Comment by francois-rozet** [comment]
> Python interactive session lines outside of actual code blocks (triple backticks) are only parsed as such when in an Examples section.

Ok that solves my problem, thanks!

However, is it common for people to actually use triple chevrons for anything else than interactive python sessions code?

**Comment by pawamoy** [comment]
I don't think it's common, and it could be enabled on demand anyway :slightly_smiling_face: 

Reading the [extensions docs](https://python-markdown.github.io/extensions/api/), I think we could use a [BlockProcessor](https://python-markdown.github.io/extensions/api/) to process blocks of text starting with `>>>` as pycon code blocks. PRs welcome, or I'll eventually get to it :slightly_smiling_face:

**Comment by JP-Ellis-KPMG** [comment]
The ability to parse `>>>` (and the follow up `...` syntax) would be incredibly useful as it integrates with the [`doctest`](https://docs.python.org/3/library/doctest.html) module of the standard library.

**Comment by pawamoy** [comment]
This is now possible thanks to the [Markdown PyCon extension](https://pawamoy.github.io/markdown-pycon/), which is immediately available to my sponsors, and has been added to the [GraviFridge goal](https://pawamoy.github.io/insiders/#1000-gravifridge-user-manual) :slightly_smiling_face:
