### ISSUE TITLE
feature: bibtex support

### ISSUE THREAD

**Issue by shenxiangzhuang** [mkdocstrings/python#180]
### Is your feature request related to a problem? Please describe.

https://github.com/shyamd/mkdocs-bibtex
After config the bibtex, we cannot cite reference by syntax `[@xxx]` in docstring.

### Describe the solution you'd like

Support the bibtex citation in docstring.

**Comment by pawamoy** [comment]
See https://github.com/shyamd/mkdocs-bibtex/issues/246 :slightly_smiling_face: If they can find a way there to make it work (while staying a plugin and not rewriting mkdocs-bibtex as a Markdown extension), I'm happy to look into it again to facilitate it from mkdocstrings (just like we plan to facilitate using mkdocs-macros in docstrings). In the meantime there's nothing we can do here, so I'll close, but feel free to discuss further :slightly_smiling_face:
