### ISSUE TITLE
bug: Classes that inherit from a parent class in another module do not inherit the docstrings unless they implement an init method

### ISSUE THREAD

**Issue by nfelt14** [mkdocstrings/python#196]
### Description of the bug
Classes that inherit from a parent class in another module do not inherit the docstrings unless they implement an init method.

I have a package with ~100 files that contain classes that inherit from other files that don't need to implement an init method, the inherited init method works just fine. However, unless I implement an unnecessary init method, the documentation doesn't generate for the child classes.

### To Reproduce
```
git clone https://github.com/nfelt14/mkdocstrings-python-issue196
cd mkdocstrings-python-issue196
python -m venv .venv
. .venv/bin/activate
pip install -r requirements.txt
mkdocs serve
```

Then check the generated site.

### Full traceback

<details><summary>Full traceback</summary>

```python
PASTE TRACEBACK HERE
```

</details>

### Expected behavior
The child class that inherits from the parent class should still show all inherited methods/attributes and the constructor.

### Environment information

```bash
python -m mkdocstrings_handlers.python.debug  # | xclip -selection clipboard
```
- __System__: Windows-10-10.0.19045-SP0
- __Python__: cpython 3.12.7
- __Environment variables__:
- __Installed packages__:
  - `mkdocs` v1.6.1
  - `mkdocstrings` v0.26.2
  - `mkdocstrings-python` v1.12.1
  - `griffe` v1.4.1

**Comment by nfelt14** [comment]
Parent page:
![image](https://github.com/user-attachments/assets/8dbe32be-1557-43d7-be5d-be23b29d7e84)

**Comment by nfelt14** [comment]
Separate child page:
![image](https://github.com/user-attachments/assets/c3d6bfc9-69df-47ad-a08a-2a30933b8c48)

**Comment by nfelt14** [comment]
Separate child page with useless init:
![image](https://github.com/user-attachments/assets/67402f5b-4ea8-4f6c-9d6f-7b9d1a52b980)

**Comment by pawamoy** [comment]
Thanks for the repro :slightly_smiling_face: 

MkDocs does not read source files in the order they're specified in the `nav`, instead it reads them and generate the corresponding pages in the "system" order (usually alphabetical).

So in this case, the child page is generated first. Therefore mkdocstrings-python first loads the `child` package, and tries to render the `Child` class. But this class inherits from a class within the `parent` package, which is not loaded. So it cannot find inherited members. This is shown by the verbose output of `mkdocs serve -v`:

```
DEBUG   -  Reading markdown pages.
DEBUG   -  Reading: index.md
DEBUG   -  Running `page_markdown` event from plugin 'autorefs'
DEBUG   -  Running `page_content` event from plugin 'autorefs'
DEBUG   -  mkdocs_autorefs: Mapping identifiers to URLs for page index.md
DEBUG   -  Reading: child.md
DEBUG   -  Running `page_markdown` event from plugin 'autorefs'
DEBUG   -  mkdocstrings: Matched '::: child'
DEBUG   -  mkdocstrings: Using handler 'python'
DEBUG   -  mkdocstrings: Collecting data
DEBUG   -  mkdocstrings: Loaded inventory from 'https://docs.python.org/3/objects.inv': 12960 items
DEBUG   -  griffe: Searching path(s) for child
DEBUG   -  griffe: Found child: loading
DEBUG   -  griffe: Loading path /media/data/dev/mkdocstrings-python-issue196/src/child.py
DEBUG   -  griffe: Base class child.parent.Parent is not loaded, or not static, it cannot be resolved
[...]
DEBUG   -  Reading: parent.md
```

To make sure inherited members can always be found for the child class, you must ["preload"](https://mkdocstrings.github.io/python/usage/configuration/general/?h=prelo#preload_modules) the parent package:

```yaml
plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          preload_modules:
          - parent
```

But then there's a second issue:

```
DEBUG   -  Reading: child.md
DEBUG   -  Running `page_markdown` event from plugin 'autorefs'
DEBUG   -  mkdocstrings: Matched '::: child'
DEBUG   -  mkdocstrings: Using handler 'python'
DEBUG   -  mkdocstrings: Collecting data
DEBUG   -  griffe: Searching path(s) for parent
DEBUG   -  griffe: Found parent: loading
DEBUG   -  griffe: Loading path /media/data/dev/mkdocstrings-python-issue196/src/parent.py
DEBUG   -  griffe: Searching path(s) for child
DEBUG   -  griffe: Found child: loading
DEBUG   -  griffe: Loading path /media/data/dev/mkdocstrings-python-issue196/src/child.py
DEBUG   -  griffe: Base class child.parent.Parent is not loaded, or not static, it cannot be resolved
```

Emphasis on the last line: `child.parent.Parent` is not loaded. Indeed `child.py` is doing a relative import:

```python
from .parent import Parent
```

This is incorrect, as the `child` package does not have a `parent` module.

So I believe you're either mis-using the src-layout, or you forgot to add an `__init__` module somehow?

**Comment by nfelt14** [comment]
My reproduction didn't follow standard layouts :)

**Comment by nfelt14** [comment]
I will try preloading my package to see if that helps with the documentation issue.

**Comment by pawamoy** [comment]
If you simply meant to import `Parent` with `from parent import Parent`, then that works fine and the `Child` class rendered in the separate page shows all inherited members :slightly_smiling_face:

**Comment by nfelt14** [comment]
My package uses absolute imports, so I will test and see if preloading works for me.

**Comment by nfelt14** [comment]
> Preloading the package works great! Thanks!

Wait, no it didn't

**Comment by nfelt14** [comment]
I am wondering if it is because these classes are using multiple inheritance. They are showing the signature of the first defined parent, but not any of the rest of the parents.

**Comment by pawamoy** [comment]
The rule of thumb is that if you want to see inherited members from class C1 which comes from package P1, C2 from P2, etc., you have to preload P1, P2, etc.

- https://mkdocstrings.github.io/python/usage/configuration/members/?h=inhe#inherited_members
- https://mkdocstrings.github.io/python/usage/configuration/general/#preload_modules

**Comment by nfelt14** [comment]
Does the preloading work recursively? If I preload a package that imports a lot of nested classes, will it preload all of the nested files?

**Comment by pawamoy** [comment]
If you want to recursively load everything you could try `load_external_modules`: https://mkdocstrings.github.io/python/usage/#load_external_modules.

**Comment by nfelt14** [comment]
Loading external modules didn't change anything. The classes that I am trying to document aren't external, they are part of the package being documented, they just are in nested folders.

This is an example: https://github.com/tektronix/tm_devices/blob/main/src/tm_devices/drivers/pi/source_measure_units/smu26xx/smu2602b.py

**Comment by pawamoy** [comment]
Can you run MkDocs in verbose mode and paste the logs relevant to Griffe? `mkdocs build -v 2>&1 | grep griffe`

**Comment by pawamoy** [comment]
Was able to serve, but hard to tell if some members are missing:

![tm](https://github.com/user-attachments/assets/91144312-6b69-443d-a285-e5bcb4faab0e)

I'd need a minimal reproducible example :confused:

**Comment by pawamoy** [comment]
>  I am wondering if it is because these classes are using multiple inheritance. They are showing the signature of the first defined parent, but not any of the rest of the parents.

Ah, missed this message. Yes only the actual signature is shown. Were you expecting to also see signatures of parent classes? Is it useful for users :thinking:?

**Comment by nfelt14** [comment]
The part I am trying to avoid is what happens if I remove the init method from the class. I think I have a solution, I am going to try it today.

**Comment by pawamoy** [comment]
If you don't implement the init method, but include inherited members, the parent init method (according to the MRO) will be rendered.

**Comment by nfelt14** [comment]
Does it keep going upwards in inheritance if its direct parent doesn't implement an init method using the parent's MRO?

**Comment by pawamoy** [comment]
Yes :relaxed: As long as these classes are loaded, which is the case if they're declared in the same package, or if you preloaded the relevant package :slightly_smiling_face:

**Comment by nfelt14** [comment]
This branch on my fork reproduces the issue: https://github.com/nfelt14/tm_devices/tree/inheritance-rearchitecture

There is a strange difference in what is shown between the smu2602b and the ss3706a page, both use multiple inheritance, but the smu2602b doesn't show any inherited methods/attributes, even though I changed the first parent class in its MRO to not have an init show it's constructor shows the proper args.

**Comment by pawamoy** [comment]
Can you elaborate *what* is the issue again? The repo and docs are quite big so it's a bit hard to navigate and guess :sweat_smile: Could you for example post the localhost links to both pages you mention (smu2602b and ss3706a)? Screenshots are fine too :slightly_smiling_face:

**Comment by pawamoy** [comment]
For some reason the Mermaid diagrams do not render anymore (syntax error) :thinking:

**Comment by nfelt14** [comment]
Something about the folder level is causing issues. When a module imports something at the same level as itself, it is able to get all the inherited docs. When it is inheriting from a folder one level up, it no longer has the docs. See the DMM folder in the drivers subpackage of that build.

http://127.0.0.1:8000/reference/tm_devices/drivers/digital_multimeters/dmm75xx/dmm7510/
src/tm_devices/drivers/digital_multimeters/dmm75xx/dmm7510.py
vs.
http://127.0.0.1:8000/reference/tm_devices/drivers/digital_multimeters/dmm6500/
src/tm_devices/drivers/digital_multimeters/dmm6500.py

Both of those classes use multiple inheritance and inherit from the same style of mixin as the first item in the MRO. However, one gets the inherited docs and the other doesn't.

**Comment by pawamoy** [comment]
OK I think I have found the issue. In your custom template at `docs/_templates/mkdocstrings/python/readthedocs/children.html.jinja`, you're using the condition `{% if obj.members %}`: try changing it to `{% if obj.all_members %}`. This is a bug we originally had in our own template, so you probably copied it over at a time it wasn't yet fixed.

**Comment by nfelt14** [comment]
Thank you! I will try this first thing Monday morning.

**Comment by nfelt14** [comment]
That fix worked! Thank you so much for putting in the time to help me debug this issue.
