### ISSUE TITLE
bug: `show_docstring_attributes: false` is non-functional

### ISSUE THREAD

**Issue by Archmonger** [mkdocstrings/python#197]
### To Reproduce
```
git clone https://github.com/reactive-python/reactpy-router/
cd reactpy-router
python -m venv .venv
.venv/bin/activate
pip install -r requirements.txt
cd docs
```
edit mkdocs.yml to enable `show_docstring_attributes: false`
```
mkdocs serve
```
Open the preview browser and navigate to any location where docstring attribute exist, such as `Reference > Types`

Watch as all the `Attributes` sections still exist.

### Full traceback
<details><summary>Full traceback</summary>
N/A
</details>

### Expected behavior
Any section containing `Attributes:` should be removed when this flag is enabled.

### Environment information

- __System__: Windows-11-10.0.22631-SP0
- __Python__: cpython 3.12.0b4 (C:\Users\Username\Repositories\reactpy-router\.venv\Scripts\python.exe)
- __Environment variables__:
- __Installed packages__:
  - `mkdocs` v1.6.1
  - `mkdocstrings` v0.26.2
  - `mkdocstrings-python` v1.12.1
  - `griffe` v1.4.1

### Additional context
Was attempting to use this to hide the docstring attributes.

To be honest I would have [preferred](https://github.com/mkdocstrings/python/pull/56#issuecomment-2418522694) to hide the section highlighted in red. There doesn't appear to be a convenient way of doing that at the moment.

![image](https://github.com/user-attachments/assets/c1388262-9246-4c03-8251-5de8907e9372)

**Comment by pawamoy** [comment]
Thanks for the report!

So, the feature works as intended, in that in doesn't render Attributes sections written in docstrings. However you're still seeing attributes table generated through the summary feature. Would you want `show_docstring_attributes: false` to also hide attributes summary tables?

**Comment by Archmonger** [comment]
Uh oh, you're correct that `show_docstring_attributes: false` definitely works now on whatever I have on `main`.

I made a lot of mkdocstrings settings changes (and source docstring refactoring) after making that initial bug report comment. I might have had some weird edge case breaking it during my testing, or perhaps I'm losing my mind.

I unfortunately didn't commit when it was broken, and I'm struggling to reproduce now.

Will close this issue with the assumption that I'm crazy. Will reopen if I can replicate in the future.
