### ISSUE TITLE
bug: Custom summary page template broken when using insiders

### ISSUE THREAD

**Issue by nfelt14** [mkdocstrings/python#205]
### Description of the bug

My custom init module summary template is broken when I switch to using the insiders version of mkdocstrings-python and griffe.

### To Reproduce

```
WRITE MRE / INSTRUCTIONS HERE
```

### Full traceback

The full traceback is too large here, I will post some screenshots. I can provide the debug output if needed.

<details><summary>Full traceback</summary>

```python
PASTE TRACEBACK HERE
```

</details>

Without insiders:
![summary_no_insiders](https://github.com/user-attachments/assets/bc5b9d43-33ec-4030-8233-c9bd537ef01a)

With insiders:
![summary_with_insiders](https://github.com/user-attachments/assets/ba6af32b-e2ae-4d24-beab-48c4be24e080)

### Expected behavior

The summary should look the same

### Environment information

```bash
python -m mkdocstrings_handlers.python.debug  # | xclip -selection clipboard
```
- __System__: Windows-10-10.0.19045-SP0
- __Python__: cpython 3.11.10
- __Environment variables__:
- __Installed packages__:
  - `mkdocs` v1.6.1
  - `mkdocstrings` v0.26.1
  - `mkdocstrings-python` v1.11.1.1.9.0
  - `griffe` v1.4.0.1.2.0

**Comment by pawamoy** [comment]
Hi @nfelt14, thanks for the report.

> My custom init module summary template is broken

Could you share your custom template then? Otherwise it will be hard to help :slightly_smiling_face:

**Comment by nfelt14** [comment]
> Hi @nfelt14, thanks for the report.
> 
> > My custom init module summary template is broken
> 
> Could you share your custom template then? Otherwise it will be hard to help 🙂

Sure, my work is in this branch: https://github.com/nfelt14/tm_devices/tree/enable-pawamoy-insiders-docs-features

My custom template is here: https://github.com/nfelt14/tm_devices/blob/enable-pawamoy-insiders-docs-features/docs/_templates/mkdocstrings/python/readthedocs/children.html.jinja

**Comment by pawamoy** [comment]
Thanks. You don't need to use the `stash_filter`, it's only useful for rendering cross-refs inside of highlighted/formatted Python code blocks. Also, the autoref `span` is deprecated in favor of a custom `autoref` element.

Try this:

```django
<tr>
                    <td>
                        <autoref identifier="{{ item.canonical_path }}" optional hover>
                            <code class="subpackage-summary-link-text">{{ item.name }}</code>
                        </autoref>
                    </td>
                    <td>{{ item.docstring.parsed[0].value.split("\n")[0]|convert_markdown(heading_level, html_id) }}</td>
                </tr>
```

**Comment by nfelt14** [comment]
That fixed the issue, thank you so much!
