### ISSUE TITLE
feature: Hide attributes, but render in summary

### ISSUE THREAD

**Issue by reteps** [mkdocstrings/python#218]
### Is your feature request related to a problem? Please describe.

I have a lot of type heavy classes I would like to document. I would like the option to only show their members in the summary table, but not show the attributes.

For example, I want to show this summary table:

![CleanShot 2024-12-20 at 22 43 22@2x](https://github.com/user-attachments/assets/47480ba9-b139-4703-86f7-db1c183a4355)

But I **do not** want to show:

![CleanShot 2024-12-20 at 22 43 53@2x](https://github.com/user-attachments/assets/34c6da95-2a5a-4173-9862-4e3f4614c435)

This is because the attributes take up too much space, and do not show any useful information.

### Describe the solution you'd like

I would like the ability to either:

- Collapse a group of stuff (e.g. attributes) inside an admonition
- Hide a section (e.g. attributes), but keep them in the summary

### Describe alternatives you've considered

I looked at the source code, and summary mirrors attributes exactly, so there is not existing way to do this without overriding templates.

**Comment by pawamoy** [comment]
Hi @reteps, thanks for the request.

When you say "summary table", do you mean you're using the [summary option](https://mkdocstrings.github.io/python/usage/configuration/members/#summary), or do you have an Attributes section written manually in your class docstring?

**Comment by pawamoy** [comment]
The long term issue with not rendering headings for attributes is that they won't be included in the objects inventory, meaning your users (and yourself!) won't be able to cross-references these attributes.

The way to solve this would be https://github.com/mkdocstrings/python/issues/133. But in the meantime, there's no configuration option to achieve what you want, and the only way is to override templates indeed.

**Comment by pawamoy** [comment]
I'll close in favor of #133 :slightly_smiling_face:
