### ISSUE TITLE
An option to control whether the admonitions in python docstring should be collapsed

### ISSUE THREAD

**Issue by asakiasako** [mkdocstrings/python#22]
**Is your feature request related to a problem? Please describe.**
When I use admonitions in python docstring like this:

```
"""
Note:
    Details ...
"""
```

I noticed that an collapsed admonitions is rendered in the browser now.

I can use `!!! note` to make a uncollapsed admonition, but this will make the docstring strange for human reading.

**Describe the solution you'd like**
The information contained in 'Note' or 'Tips' or other admonitions are usually important information, and we don't want our users to miss them, so I think at least we have a choise to choose whether it should be collapsed.

----------
Platform: Windows 10
mkdocstrings == 0.19.0
mkdocstrings-python == 0.7.0
griffe == 0.20.0

I don't know if I described the situation clearly 😂

**Comment by pawamoy** [comment]
Thanks for the report! I was able to replicate. I went with `details` + `summary` HTML tags for admonitions, but I see now that other admonitions use divs and classes. We can either change the admonition template to match it, or users can override it.

From this:

```jinja+html
{{ log.debug("Rendering admonition") }}
<details class="{{ section.value.kind }}">
  <summary>{{ section.title|convert_markdown(heading_level, html_id, strip_paragraph=True) }}</summary>
  {{ section.value.contents|convert_markdown(heading_level, html_id) }}
</details>
```

...to this:

```jinja+html
{{ log.debug("Rendering admonition") }}
<div class="admonition {{ section.value.kind }}">
  <p class="admonition-title">{{ section.title|convert_markdown(heading_level, html_id, strip_paragraph=True) }}</p>
  {{ section.value.contents|convert_markdown(heading_level, html_id) }}
</div>
```

Not sure what is the most sensible solution :confused: 
@facelessuser, maybe you could give us some hindsight? (is it OK if I ping you like that by the way?)

**Comment by pawamoy** [comment]
Argh, for some reason I thought the `admonition` extension was part of PyMdown Extensions... I guess the similar syntax and [this paragraph](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#collapsible-blocks) is the reason why. My bad. I think I'll stick with details and default to `open=""`.

**Comment by lukaszmoroz** [comment]
+1 for making `open` default.

> I also don't see a clean way to control it from the markup itself (from within the docstring) confused Open to suggestions.

Maybe allow to control it through options: either the default behavior, or each kind separately, or both:

```jinja2
<!-- templates/material/_base/docstring/admonition.html -->

{% set admonition_config = (config.admonitions | default({}))[section.value.kind] | default({}) %}
{% set open = admonition_config.open | default(config.admonitions_default_open) %}

<details class="{{ section.value.kind }}" {% if open %}open{% endif %}>
    <summary>{{ section.title|convert_markdown(heading_level, html_id, strip_paragraph=True) }}</summary>
    {{ section.value.contents|convert_markdown(heading_level, html_id) }}
</details>
```

And then:
```yaml
# mkdocs.yml

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            admonitions_default_open: false
            admonitions:
              see-also: { open: true }
```

**Comment by levzlotnik** [comment]
Hey mkdocstrings team, thank you so much for making this extension! It's really cool and helped me in my work significantly!

I ran into the same small issue while writing documentation for my project, is there any plan to support configurable admonitions like in this discussion? Or is there a temporary workaround I can apply in my project by including some JS/CSS?

**Comment by asakiasako** [comment]
> Hey mkdocstrings team, thank you so much for making this extension! It's really cool and helped me in my work significantly!
> 
> I ran into the same small issue while writing documentation for my project, is there any plan to support configurable admonitions like in this discussion? Or is there a temporary workaround I can apply in my project by including some JS/CSS?

For now, I write a workaround in python which modifies the outputed html files directly. First output the site and then run the workaround. You can see if it can help you.

``` python
def fix_admonition_collapse():
    print('=======================\nfix_admonition_collapse\n=======================')
    api_names = ['abc', 'models']

    PATTERN = re.compile(
        r'<details class="(.*?">\n'
        r'\s*)<summary>(?!Source code in)(.*?)<\/summary>(\n'
        r'(.*\n)*?'
        r')<\/details>'
    )

    for n in api_names:
        filepath = f'./site/api/{n}/index.html'
        with open(filepath, 'r') as fp:
            s = fp.read()
        c = len(PATTERN.findall(s))
        new_s = PATTERN.sub(r'<div class="admonition \1<p class="admonition-title">\2</p>\3</div>', s)
        with open(filepath, 'w') as fp:
            fp.write(new_s)
        print(f'{c} modifications in {filepath}')
    print('')
```

>

**Comment by IceBotYT** [comment]
> First output the site and then run the workaround.

How would I go about this using GitHub Actions?

**Comment by inpbox** [comment]
> Argh, for some reason I thought the `admonition` extension was part of PyMdown Extensions... I guess the similar syntax and [this paragraph](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#collapsible-blocks) is the reason why. My bad. I think I'll stick with details and default to `open=""`.

Thanks for an awesome project. I've got:
```
mkdocs 1.4.2
mkdocstrings 0.20.0
mkdocs-material 9.0.12
```

and I see the "details" in the admonitions as "collapsed" and not "open" for the final html output.

![python_mkdocstrings_admonitions_collapsed](https://user-images.githubusercontent.com/19344780/219677168-690852f9-d3ef-4d3b-bab8-4940b7b1a0f3.png)

Any way to override this setting, or is it on the todo-list to be implemented?

**Comment by pawamoy** [comment]
Fixed in https://github.com/mkdocstrings/python/commit/79cd153cfceec860f6ce08d30817c21031983238, will release soon.
