### ISSUE TITLE
show all the source code automatically inside a package in a single page

### ISSUE THREAD

**Issue by copdips** [mkdocstrings/python#23]
**Is your feature request related to a problem? Please describe.**
With the old legacy python handler, we set only the root package, for example, `:::demo`, then all the sub-modules, files inside of the `demo` package will be discovered and displayed automatically in this single page.

Now with the new python handler, `mkdocs build` doesn't raise any error, but when I preveiw the result with `mkdocs serve`, it renders just a blank page.

But if I go deeper to the file level, it will render it, but just only one python file each time, for eample `:::demo.sub_package1.sub_file1`

**Describe the solution you'd like**
make backward compatible with an option in `mkdocs.yml` config file, otherwise, with the new version, we should create as many pages or line sto specifiy each python source code file one by one, and with previous legacy python handler, we just need to specify the root package name like `:::demo`, this save us a lot of time, because we have many source code files.

**Describe alternatives you've considered**

**Additional context**

**Comment by pawamoy** [comment]
Yes we recently changed the default value for `show_submodules` to False. I believe it's a more sensible default (as it's the most common use-case). Just set the `show_submodules` option to `true`, either in your global mkdocs.yml configuration or below your `::: demo` autodoc instruction :slightly_smiling_face:

**Comment by copdips** [comment]
> Yes we recently changed the default value for `show_submodules` to False. I believe it's a more sensible default (as it's the most common use-case). Just set the `show_submodules` option to `true`, either in your global mkdocs.yml configuration or below your `::: demo` autodoc instruction 🙂

thx a lot, works like a charm!
