### ISSUE TITLE
Positional-only arguments are mishandled in signatures

### ISSUE THREAD

**Issue by FasterSpeeding** [mkdocstrings/python#25]
**Describe the bug**
Positional-only arguments are mishandled in signatures with `/` always being put at the start of a signature with positional-only arguments regardless of how many arguments are positional only.

**To Reproduce**
With the following test code being targeted by mkdocstrings

```py
# test.py
def bar(foo: str, baz: int, /, *, bar: int = 123) -> None:
    """meow"""

```

and the following mkdocs.yml

```yml
# mkdocs.yml
site_name: "Docs"
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      watch:
        - test.py
```

build documentation from this module and watch it place `/` at the start of bar's signature as shown in the following screenshot.

**Expected behavior**
`/` should appear after `baz` in the signature.

**Screenshots**

![image](https://user-images.githubusercontent.com/11181703/173230490-2132816b-e2ac-42a1-88a1-7ac880193f4b.png)

**System (please complete the following information):**
- `mkdocstrings-python` version: 0.7.0
- mkdocstrings version: 0.19.0
- griffe version: 0.20.0
- mkdocs version: 1.3.0
- Python version: 3.10
- OS: Windows

**Additional context**
This leads to an error being raised in cases where black is used to reformat function signatures with positional only arguments as `/` cannot be the first argument of a function syntax wise.

I can't really read this code but from what I can tell the responsible code might be here https://github.com/mkdocstrings/python/blob/bc1a8aefe684444037600b9a52be2ad0f3e02e38/src/mkdocstrings_handlers/python/templates/material/_base/signature.html#L15-L17 (where it's adding in `/` the moment it finds a positional only argument that isn't named `self` or `cls` rather than waiting until it reaches the end of the positional only arguments). I did try griffe with the example code and it seemed to be handling positional-only arguments properly.

**Comment by pawamoy** [comment]
Hi, thank you so much for the very detailed report and investigation! This is greatly appreciated.

I was able to replicate with the example you provided :+1:
This should be fixed in version 0.7.1 :slightly_smiling_face: 
Closing! Let me know if something is wrong.
