### ISSUE TITLE
ToC names overflow if they are too long

### ISSUE THREAD

**Issue by Kigstn** [mkdocstrings/python#29]
**Describe the bug**
Entries in the ToC can overflow if they are too long. This results in them being cut off.

**To Reproduce**
Give a class a long name and watch the ToC

**Expected behavior**
Either
1) A scroll wheel appears
2) The name is cut-off with dots -> ` CommunityContentRouteHttp...`

Option 2 feels the best from a UX standpoint IMO.

**Screenshots**
![image](https://user-images.githubusercontent.com/38250010/176492078-08f8b4d0-2312-4c2e-91a8-10f8f42ba512.png)
![image](https://user-images.githubusercontent.com/38250010/176492123-22101ceb-fd99-4e9e-911e-f01a74fa6681.png)

**System (please complete the following information):**
- `mkdocstrings-python` version: [0.7.1]
- Python version: [3.10]
- OS: [Windows]
- Theme: `material`

**Additional context**
See [here](https://bungio.readthedocs.io/en/latest/API%20Reference/HTTP/Bungie%20Routes/community_content/) for a live example

**Comment by pawamoy** [comment]
That would be a request for the Material for MkDocs theme I guess :thinking:

Could you try to see if there's such a request there? And otherwise open one to see what they think about it?

**Comment by Kigstn** [comment]
Sure, will do. Thanks
