### ISSUE TITLE
Evaluate signature-changing decorators

### ISSUE THREAD

**Issue by lukaszmoroz** [mkdocstrings/python#30]
**Is your feature request related to a problem? Please describe.**
My issue with this handler is sort of reverse of e.g. https://github.com/mkdocstrings/mkdocstrings/issues/162, https://github.com/mkdocstrings/mkdocstrings/issues/308.

I have a decorator that overrides the wrapped function's `__annotations__` and `__doc__`. But since the new `griffe` parser doesn't evaluate modules, `mkdocstrings` cannot pick up those, making it impossible to use it with signature-changing decorators.

**Describe the solution you'd like**
Make it maybe possible to evaluate certain decorators during parsing.

**Describe alternatives you've considered**
The old `python-legacy` handler works fine in this regard (although it has other issues which prevent me from using it).

**Comment by analog-cbarber** [comment]
I have some decorators like this as well. In my case, they mostly just add additional information to the doc string that I wish could show up in the generated documentation.

**Comment by pawamoy** [comment]
If your decorator are not too dynamic, you can achieve this with a visitor extension.
When visiting a class or function definition, if it is decorated with your decorator, you can update the docstring instantiated by Griffe. If you give me an example of how your decorator is used, I can elaborate :slightly_smiling_face:

**Comment by pawamoy** [comment]
Thanks for the example! Yes, you understand correctly.

OK, here is how the extension would look:

```python
import ast

from griffe.extensions import VisitorExtension
from griffe.dataclasses import Function
from griffe.agents.nodes import safe_get_expression


class MagicExtension(VisitorExtension):
    def visit_functiondef(self, node: ast.FunctionDef) -> None:
        current_func: Function = self.visitor.current.members[node.name]
        magic_decorator = "yourpkg.magic"
        for decorator_node in node.decorator_list:
            expression = safe_get_expression(
                decorator_node,
                parent=current_func,
                parse_strings=False,
                log_level=None,
            )
            decorator = expression.full.split("(", 1)[0]
            if decorator == magic_decorator:
                current_func.setter = Function(...)  # represent your setter
                current_func.deleter = Function(...)  # represent your deleter
                current_func.returns = ...  # maybe change the getter return annotation
                if current_func.docstring:
                    current_func.docstring.value += ...  # update the getter docstring
```

**Comment by analog-cbarber** [comment]
Thanks for the explanation.

**Comment by pawamoy** [comment]
Oh, I forgot to show you how to use it. If your extension code is in `magic_ext.py`:

```yaml
# mkdocs.yml
plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          extensions:
          - magic_ext.py
```

**Comment by AntoineD** [comment]
@pawamoy I have a quite similar situation when using [docstring-inheritance](https://antoined.github.io/docstring-inheritance/), do you see a way forward to support it?

**Comment by pawamoy** [comment]
Check out the full example of the new extension system in Griffe: https://mkdocstrings.github.io/griffe/extensions/#full-example. IMO it's a good base for what you want to accomplish. If you get the actual object with `dynamic_import`, you can then use `inspect.getdoc` to get the inherited docstring. Note that we plan on supporting this natively at some point (inheriting docstrings from parent classes) :slightly_smiling_face:

**Comment by AntoineD** [comment]
> Check out the full example of the new extension system in Griffe: https://mkdocstrings.github.io/griffe/extensions/#full-example. IMO it's a good base for what you want to accomplish. If you get the actual object with `dynamic_import`, you can then use `inspect.getdoc` to get the inherited docstring.
> 
> Note however that this example is akin to brute-force. It's probably possible to obtain the same effect with static analysis only (i.e. without importing anything). For example in the `on_module_members` hook, you could iterate on classes, check if they specify a given metaclass, and update methods' docstrings accordingly. That's a bit more work. And Griffe is not 100% ready for such advanced static extensions (but we're getting there by improving our ["expressions"](https://mkdocstrings.github.io/griffe/reference/griffe/expressions/)).
> 
> Also note that we plan on supporting this natively at some point (inheriting docstrings from parent classes) 🙂

This is awesome! The full example seems to be a perfect starting point, thanks a lot.
BTW, the user and dev docs of mkdocstrings et al look far better than the sphinx ones, kudos!

**Comment by pawamoy** [comment]
Ha, thank you much... That goes right to my heart 😭 Writing good docs is so freaking hard, I put a lot of effort into it so reading this just made my day. Thanks ♥️

**Comment by AntoineD** [comment]
@pawamoy I came up with that, would you mind to give it a quick review?
```python
class DynamicDocstrings(Extension):

    def on_class_members(self, node: ast.AST | ObjectNode, cls: Class) -> None:
        if isinstance(node, ObjectNode):
            return  # skip runtime objects, their docstrings are already right
        for member in cls.members.values():
            self.__on_instance(member)

    def on_class_instance(self, node: ast.AST | ObjectNode, cls: Class) -> None:
        if isinstance(node, ObjectNode):
            return  # skip runtime objects, their docstrings are already right
        self.__on_instance(cls)

    def __on_instance(self, obj: Object) -> None:
        # import object to get its evaluated docstring
        try:
            runtime_obj = dynamic_import(obj.path)
        except ImportError:
            logger.debug(f"Could not get dynamic docstring for {obj.path}")
            return

        try:
            docstring = runtime_obj.__doc__
        except AttributeError:
            logger.debug(f"Object {obj.path} does not have a __doc__ attribute")
            return

        if docstring is None:
            return

        # update the object instance with the evaluated docstring
        docstring = inspect.cleandoc(docstring)
        if obj.docstring:
            obj.docstring.value = docstring
        else:
            obj.docstring = Docstring(docstring, parent=obj)
```

**Comment by pawamoy** [comment]
Yep, looks good, though you could probably just implement `on_class_members` and call `__on_instance(cls)` there. The `on_class_members` event will always be triggered, even when a class has no members.

```python
    def on_class_members(self, node: ast.AST | ObjectNode, cls: Class) -> None:
        if isinstance(node, ObjectNode):
            return  # skip runtime objects, their docstrings are already right
        self.__on_instance(cls)
        for member in cls.members.values():
            self.__on_instance(member)
```

**Comment by AntoineD** [comment]
Thank you.

I found an issue with the `Returns` that is not well rendered when it is inherited. I'll investigate.

**Comment by pawamoy** [comment]
I'll close this. Functions decorated with custom signature-changing decorators should be handled with extensions. Decorators from the standard library should have their respective built-in extensions though, but we can deal with that in other issues.
