### ISSUE TITLE
ValueError: 'restructured-text' is not a valid Parser using new `python` handler

### ISSUE THREAD

**Issue by omri374** [mkdocstrings/python#31]
**Describe the bug**
When building the mkdocs site using the new `python` handler, I get an exception saying `ValueError: 'restructured-text' is not a valid Parser`. This does work when using the `python-legacy` handler

**To Reproduce**
1. Run `pip install mkdocstrings[python]`
2. Run `mkdocs serve`

**Expected behavior**
Mkdocs builds successfully and parses `restructured-text` docstrings

**System (please complete the following information):**
```
mkdocs==1.3.0
mkdocs-autorefs==0.4.1
mkdocs-jupyter==0.20.1
mkdocs-material==8.2.11
mkdocs-material-extensions==1.0.3
mkdocstrings==0.19.0
mkdocstrings-python==0.7.1
```

I assume this relates to the "Note that..." here: https://mkdocstrings.github.io/handlers/overview/#about-the-python-handlers

**Comment by pawamoy** [comment]
`restructured-text` was renamed `sphinx` in the new parser :slightly_smiling_face: 
This is documented just a bit below the docs section you mentioned :smile: 
Closing!
