### ISSUE TITLE
ERROR - mkdocstrings: script could not be found

### ISSUE THREAD

**Issue by MathKlim** [mkdocstrings/python#35]
**Describe the bug**
I use mkdocstrings + mkdocs-material to document my package. However, when I try to build or serve the documentation, mkdocstrings cannot find my modules.

I end with the following error : 

```shell
❯ mkdocs serve
INFO     -  Building documentation...
INFO     -  Cleaning site directory
ERROR    -  mkdocstrings: azure_helper.steps.create_aml_env could not be found
ERROR    -  Error reading page 'steps/create_aml_env.md':
ERROR    -  Could not collect 'azure_helper.steps.create_aml_env'

Aborted with a BuildError!
```

**To Reproduce**
1. Go to https://github.com/Klimorg/azure-mlops-helper and clone the repo,
2. Create a venv and install the package via `python -m install -e . --no-cache-dir`,
3. Install doc requirements `python -m pip install requirements-doc.txt`
4. Run command `mkdocs serve`
6. See error

**Expected behavior**
 The documentation should be build, mkdocs should find my modules and catch the dosctrings.

According to https://mkdocstrings.github.io/python/usage/#finding-modules it seems I am in this situation : "mkdocs.yml in root, package in root "

```yaml
plugins:
    - search:
          lang: fr
    - mkdocstrings:
        handlers:
            python:
                paths: [.]  # actually not needed, default
```

**Screenshots**
Here is a screenshot to see my package config.

![mkdocstrings_bug](https://user-images.githubusercontent.com/48051974/185613594-ca28612b-b734-45dc-b874-db2f957f6d0b.png)

**System (please complete the following information):**

```
mike==1.1.2
mkdocs==1.3.1
mkdocs-material==8.3.9
mkdocstrings==0.19.0
mkdocstrings-python==0.7.1
```
- Python version: 3.8
- OS:Ubuntu 20.4

**Additional context**

**Comment by pawamoy** [comment]
Hello, thanks for the report.

Running mkdocs in verbose mode:

```console
$ mkdocs serve -v
DEBUG    -  mkdocstrings: Matched '::: azure_helper.steps.create_aml_env'
DEBUG    -  mkdocstrings: Using handler 'python'
DEBUG    -  mkdocstrings: Collecting data
DEBUG    -  griffe: Found azure_helper: loading
DEBUG    -  griffe: Loading path azure_helper/__init__.py
DEBUG    -  griffe: Loading path azure_helper/logger.py
DEBUG    -  griffe: Loading path azure_helper/utils/__init__.py
DEBUG    -  griffe: azure_helper/steps/train.py is not importable. Missing __init__ module?
DEBUG    -  griffe: azure_helper/steps/deploy_aml_model.py is not importable. Missing __init__ module?
DEBUG    -  griffe: azure_helper/steps/create_aml_env.py is not importable. Missing __init__ module?
DEBUG    -  griffe: azure_helper/steps/score.py is not importable. Missing __init__ module?
DEBUG    -  griffe: azure_helper/steps/create_aml_experiment.py is not importable. Missing __init__ module?
DEBUG    -  griffe: azure_helper/steps/create_data.py is not importable. Missing __init__ module?
DEBUG    -  griffe: Loading path azure_helper/utils/blob_storage_interface.py
DEBUG    -  griffe: Loading path azure_helper/utils/aml_interface.py
DEBUG    -  griffe: azure_helper/scripts/call_web_service.py is not importable. Missing __init__ module?
DEBUG    -  griffe: Iteration 1 finished, 0 aliases resolved, still 0 to go
ERROR    -  mkdocstrings: azure_helper.steps.create_aml_env could not be found
ERROR    -  Error reading page 'steps/create_aml_env.md':
ERROR    -  Could not collect 'azure_helper.steps.create_aml_env'
```

Indeed you don't have an `__init__.py` module in `azure_helper/steps`, is that intentional?

**Comment by MathKlim** [comment]
Well, shamlessly admitting this is not intentional, and it's a mistake on my side. I should have catch it sooner.  Thank you.

**Comment by pawamoy** [comment]
No problem, I made the same mistake multiple times, no shame here :)
