### ISSUE TITLE
Display overwritten/inherited methods in sublcasses

### ISSUE THREAD

**Issue by famura** [mkdocstrings/python#40]
**Is your feature request related to a problem? Please describe.**
Consider the following scenario. We have a base class called `A` and one or multiple derived classes `B1`, `B2`, ... The base class `A` implements a method `func`. After building the doc, we can reference this method with `[path.to.A.func][]`. Let's further consider that `B1` and the others overwrite `func` and we would like to reference `B1.func` in the doc of `B2.func`. However, if I am not completely mistaking, we can not do this since they are not displayed in the doc page because `func` is already defined in `A`.

**Describe the solution you'd like**
An option just like the ones listed [here](https://mkdocstrings.github.io/python/usage/), e.g. `show_inherited_members`, that prints the members of subclasses, and provides anchors to them.

**Describe alternatives you've considered**
There are none.

**Comment by pawamoy** [comment]
I think this issue is solved now that we have support for inherited members. Let me know if I got it wrong and I'll reopen.
