### ISSUE TITLE
module 'mkdocstrings_handlers.python' has no attribute 'get_handler'

### ISSUE THREAD

**Issue by nani1149** [mkdocstrings/python#41]
mkdocs serve is giving this erro 

module 'mkdocstrings_handlers.python' has no attribute 'get_handler'

**Comment by pawamoy** [comment]
Hi, could you tell us what version of every related package you're using (mkdocs, mkdocstrings, mkdocstrings-python), and show us the output of `mkdocs build -v` please?

**Comment by nani1149** [comment]
@pawamoy Here is the list 
![image](https://user-images.githubusercontent.com/19945738/198108606-3e235813-586c-4411-a951-5aa343765af7.png)
![image](https://user-images.githubusercontent.com/19945738/198108737-a7fa929b-ccbd-4089-b7f4-e27b25348ece.png)

**Comment by pawamoy** [comment]
Please use text rather than images, and try not to truncate the traceback. We need the full traceback.
In the meantime you can try to delete and recreate your virtualenv.
