### ISSUE TITLE
path does not working if cwd is not the cfg file location

### ISSUE THREAD

**Issue by veghdev** [mkdocstrings/python#42]
**Describe the bug**
path does not working if cwd is not the cfg file location since path accepts glob

**To Reproduce**
1. move the mkdocs.yml into a folder, for example tools/mkdocs
2. run command mkdocs build -f ./tools/mkdocs/mkdocs.yml -d ../../site
3. See error

**Comment by pawamoy** [comment]
Ha, indeed, I didn't think about that when merging the feature. Globs must be expanded, and for that the CWD must be right. I'll review you PR, thanks!

**Comment by pawamoy** [comment]
Fixed in 0.8.1.
