### ISSUE TITLE
Option to include parameters that aren't in the docstring

### ISSUE THREAD

**Issue by FelixMW-CM** [mkdocstrings/python#46]
**Is your feature request related to a problem? Please describe.**
Where I work, we try to avoid redundant docstrings, i.e. parameter names are as self-explanatory as possible, and they are type-annotated. However, those parameters then don't appear in mkdocstrings' rendered table/list/spacy of parameters.

**Describe the solution you'd like**
An option to show all parameters of a function, even if some parameters aren't explicitly mentioned in the docstring. Likewise for the return type, if it is specified in the code.

**Comment by pawamoy** [comment]
I'll close this as out-of-scope. Docstring standards are already quite hard to support correctly, plus the code isn't designed to fetch parameters from signatures when rendering docstring sections. There would be several edge-cases, like, should we render a section with all params if none of them are documented?, etc.. Finally we already have lots of options and I would like to avoid adding too many :slightly_smiling_face:
