### ISSUE TITLE
Automatic generation of markdown files for all modules from src

### ISSUE THREAD

**Issue by kangshung** [mkdocstrings/python#54]
**Is your feature request related to a problem? Please describe.**
Hey, I would like to automatically generate markdown files for all modules in a directory, recursively.

Afaik, their content should be in the ::: my_library.my_module.my_class format.

For now, I believe I need to manually create them for each module. When the complexity of the project grows, it's becoming problematic and unreasonable to add a new file manually.

**Describe the solution you'd like**
Any solution that will automatically generate these files so that I can add them to a navbar in my mkdocs.yml.

**Comment by pawamoy** [comment]
Check out this recipe on our documentation site: https://mkdocstrings.github.io/recipes/#automatic-code-reference-pages. I believe this solves your issue for now, so I'll close. We might provide something more integrated in the future.
