### ISSUE TITLE
Summary Tables

### ISSUE THREAD

**Issue by danchitnis** [mkdocstrings/python#55]
Hello, and thanks for the brilliant work. I was wondering if there is an option to make summary tables similar to [here](https://pyscpi.readthedocs.io/en/latest/autoapi/pyscpi/keysight/osc/index.html) as opposed to what is currently available in mkdocstrings [here](https://danchitnis.github.io/pyscpi/API/osc/)

A summary table, make a summary of all the entries of that page (i.e. classes, APIs, etc.) at the top of the page rather than a long list of detailed APIs immediately in the beginning, which could startle the users.

**Comment by pawamoy** [comment]
Hello, thanks for the request :slightly_smiling_face: 
It's not possible yet but it's a good idea :+1:

**Comment by pawamoy** [comment]
This is now implemented as part of mkdocstrings-python Insiders 1.2.0, see the docs: https://mkdocstrings.github.io/python/usage/configuration/members/#summary :slightly_smiling_face:
