### ISSUE TITLE
Dataclasses syntax

### ISSUE THREAD

**Issue by nrbnlulu** [mkdocstrings/python#58]
**Describe the bug**
```py
@dataclass
class Foo:
    bar: str
    """documentation for bar"""
```
Here bar is recognized by mkdocstring-python as a class-variable, it should parsed like arguments

**Screenshots**
![image](https://user-images.githubusercontent.com/88795475/215974674-4df3fd86-84c3-4cf4-8440-f013efc62b53.png)

While this is what I would expect:
![image](https://user-images.githubusercontent.com/88795475/215975035-4502610c-9fb7-4a37-8d43-2476ebb6b94d.png)

Note that when implementing this *any* library that uses [PEP 681](https://peps.python.org/pep-0681/) should treated the same

**Comment by pawamoy** [comment]
I don't disagree :slightly_smiling_face: I'll have to see if there are special cases to handle though.
In the meantime you can document these dataclass attributes with a Parameters section in the class' docstring itself.

**Comment by gilfree** [comment]
Hi, What is your opinion about supporting not just `dataclasses` but all the dataclass-like objects as defined in https://peps.python.org/pep-0681/ ?

That will cover at least dataclasses, attrs and pydantic objects

**Comment by pawamoy** [comment]
I'd have to read the PEP more carefully, but once we get inheritance working it should be possible yes.

**Comment by pawamoy** [comment]
You might be interested in this Griffe extension: https://github.com/tlambert03/griffe-fieldz

**Comment by pawamoy** [comment]
Griffe recently added much better support for dataclasses, this should be fixed.
