### ISSUE TITLE
Black fails if types are strings

### ISSUE THREAD

**Issue by samuelcolvin** [mkdocstrings/python#6]
**Describe the bug**

Strings seem to have html escaped before being passed to black.

**To Reproduce**

Add some code like

https://github.com/samuelcolvin/dirty-equals/blob/c690abbb32e5893d3bb2634e1345ab30a2f46791/dirty_equals/_dict.py#L39-L45

Where the return type is a string.

On build you'll get an error like:

```
  File "/Users/samuel/code/dirty-equals/env/lib/python3.10/site-packages/black/parsing.py", line 132, in lib2to3_parse
    raise exc from None
black.parsing.InvalidInput: Cannot parse: 1:162: def settings(self, *, strict: Optional[bool] = None, partial: Optional[bool] = None, ignore_values: Union[None, Container[Any], Callable[[Any], bool]] = None) -> &#39;IsDict&#39;: pass
```

**System (please complete the following information):**
- Python version: 3.10
- OS: Linux/macos

docs requirements:

```
black==21.12b0
mkdocs==1.2.3
mkdocs-material==8.2.1
mkdocstrings[python]==0.18
```

**Comment by pawamoy** [comment]
Thanks for the report! Fixed in 0.6.5 :slightly_smiling_face:
