### ISSUE TITLE
The navigation path must not be empty

### ISSUE THREAD

**Issue by ammar-khan** [mkdocstrings/python#63]
**Describe the bug**
When autogenerating Navigation I am getting following error:

raise ValueError(f"The navigation path must not be empty (got {keys!r})")
ValueError: The navigation path must not be empty (got ())

**To Reproduce**

import mkdocs_gen_files
nav = mkdocs_gen_files.Nav()

**Expected behavior**
It should not throw this exception as per example provided.

**Screenshots**

**System (please complete the following information):**
- mkdocstrings = { version = ">=0.20.0", extras = ["python"] }
- Python version: 3.9
- OS: [Windows]

**Additional context**
cur = self._data
if not keys:
   raise ValueError(f"The navigation path must not be empty (got {keys!r})")

**Comment by pawamoy** [comment]
Thanks for reporting back and closing the issue! Glad you found the solution :tada:
