### ISSUE TITLE
Provide documentation of syntax and decision logic for filter

### ISSUE THREAD

**Issue by alexvoss** [mkdocstrings/python#66]
Hi,

I have been trying to get mkdocstrings to document only public methods in my class. This means filtering our anything that starts with two underscores, except constructors. 

Was missing information about the syntax of the filters. Is what follows the optional exclamation mark a regular expression? That would mean that the [default](https://mkdocstrings.github.io/python/usage/) ["!^_[^_]"] would filter out anything with a single underscore. My understanding is that that would be "protected" members but not "private" ones. 

What would also need documenting is the logic that is applied when interpreting a list of filters. It looks like later filters take precedence? I was able to get only public members and constructors documented using the following configuration. Is this how it is intended? (I know the first filter expression is somewhat crude.)

```
options:
  filters:
    - "!__"
    - "__init__"
```

Cheers, Alex

**Comment by pawamoy** [comment]
Hi Alex, thanks a lot, this is valuable feedback. You guessed it right: later filters take precedence, allowing to refine the previous filters. This should definitely be better documented. I labeled the issue with "documentation", I should be able to get to it soon :slightly_smiling_face:

**Comment by pawamoy** [comment]
What do you think of https://mkdocstrings.github.io/python/usage/configuration/members/#filters?

**Comment by alexvoss** [comment]
Great, that looks fine to me. Keep up the great work!
