### ISSUE TITLE
Allow customizing GriffeLoader.allow_inspection

### ISSUE THREAD

**Issue by BlueGlassBlock** [mkdocstrings/python#68]
When utilizing native extensions, griffe will first use ` inspect` to load native extension as a base, however that may produce confusing result by "leaking" APIs from native level, or produce confusing tag on methods/properties. So I think allowing toggling inspection is useful to make griffe only analyze modules statically.

> For reference, see my testing repo: https://github.com/BlueGlassBlock/mkdocstrings-native-test

**Comment by pawamoy** [comment]
Thanks, good use-case for Griffe's `allow_inspection` option :+1: Thanks for the PR!
