### ISSUE TITLE
Don't show the implicit `self`  parameter in the function signature

### ISSUE THREAD

**Issue by bear24rw** [mkdocstrings/python#7]
**Is your feature request related to a problem? Please describe.**

I would like to not show the implicit `self` parameter in the function signatures.  Since the documentation is most often read by a user of the object there is no need to show them to the explicit `self` parameter. The built in python `help()` docstring renderer does not show it. 

**Describe the solution you'd like**

A config option to disable show `self` would be ideal. Defaulting to "dont show `self`" would be even better.  

**Describe alternatives you've considered**

An alternative is to not have a config option and just never show it.

**Comment by bear24rw** [comment]
I think what I am after can be achieved with this patch. I'd argue that this is the correct thing to do by default for class methods.

```patch
diff --git a/src/mkdocstrings_handlers/python/templates/material/_base/class.html b/src/mkdocstrings_handlers/python/templates/material/_base/class.html
index 8f47fb8..6a27c08 100644
--- a/src/mkdocstrings_handlers/python/templates/material/_base/class.html
+++ b/src/mkdocstrings_handlers/python/templates/material/_base/class.html
@@ -105,10 +105,12 @@
         {% endif %}
       {% endif %}

-      {% with obj = class %}
-        {% set root = False %}
-        {% set heading_level = heading_level + 1 %}
-        {% include "children.html" with context %}
+      {% with no_self = True %}
+        {% with obj = class %}
+          {% set root = False %}
+          {% set heading_level = heading_level + 1 %}
+          {% include "children.html" with context %}
+        {% endwith %}
       {% endwith %}
     </div>
```

**Comment by pawamoy** [comment]
You're probably right, we're documenting APIs and users never have to pass `self` so I guess it'd be reasonable to always hide it.
Then `cls` should be hidden as well right?

**Comment by bear24rw** [comment]
> Then cls should be hidden as well right?

I believe so!

**Comment by pawamoy** [comment]
Done in version 0.6.6
