### ISSUE TITLE
The `yield` type of a (async) generator should be the inner type, not the iterator type

### ISSUE THREAD

**Issue by llucax** [mkdocstrings/python#75]
**Describe the bug**
When writing generators, the yield type includes the `Iterator` type.

**To Reproduce**
Example file:
```py
from typing import Iterator


def a_generator() -> Iterator[int]:
    """Generate a number.

    Yields:
        A number.
    """
    yield 1
```
**Expected behavior**
The yield type should be the *inner* type, for example for `Iterator[int]` it should be `int`.

**Screenshots**
In this case the `yield`ed type is actually `int`, not `Iterator[int]`.

![image](https://github.com/mkdocstrings/python/assets/1031485/f4c3cde3-37f1-4726-a1da-9ca642f01a6e)

**System (please complete the following information):**
- `mkdocstrings-python` version: 1.1.2
- Python version: e.g. 3.11
- OS: Linux (Debian testing)

**Comment by pawamoy** [comment]
Hello, thanks for the report. I agree :slightly_smiling_face: We should do the same for Receives. I just pushed a fix and will try to release soon.

**Comment by llucax** [comment]
Great, thanks!
