### ISSUE TITLE
feat: Ability to ignore or warn instead of raising a collection error exception.

### ISSUE THREAD

**Issue by jdpatt** [mkdocstrings/python#81]
As the default handler of mkdocstrings, it assumes that all `:::` identifiers are meant to be consumed by it.  If it is unable to import the python module, it raises a `CollectionError` and stops. This is okay where you are just using different handlers to parse different sources.  The issue occurs when it cannot be consumed by mkdocstrings.  Other mkdoc extensions can use the `:::` to denote other item or feature.   One example is `mkdocs-click` which has the following format:  

```markdown
::: mkdocs-click
    :module: app.cli
    :command: main
```
```
DEBUG    -  mkdocstrings: Matched '::: mkdocs-click'
DEBUG    -  mkdocstrings: Using handler 'python'
DEBUG    -  mkdocstrings: Collecting data
DEBUG    -  griffe: Could not find mkdocs-click
DEBUG    -  griffe: Trying inspection on mkdocs-click
ERROR    -  mkdocstrings: No module named 'mkdocs-click'
ERROR    -  Error reading page 'index.md':
ERROR    -  Could not collect 'mkdocs-click'
```

**Describe the solution you'd like**
Trying to think of a few possible solutions:

- Add an global ignore option to the python handler and let users tell mkdocstrings-python which identifiers to ignore.

```yaml
plugins:
- mkdocstrings:
    handlers:
      python:
        ignore: [
          mkdocs-click # Do not collect this
        ]
```

- Change the exception to a warning instead. Potentially with a strict flag so that it should fail.
- Add some type of flag on the identifier for mkdocstring-python to ignore but this will likely conflict with other packages at some point.

```yaml
::: mkdocs-click
    :module: app.cli
    :command: main
    mkdocstring-ignore: true
```

Thinking more on it.  Maybe the ignore should be at the mkdocstiring level instead of the handler.  We do have the `handler` option to tell an identifier which handler to use.  So if it is intended for a handler, we can control who gets it.  I do not know if we have the ability to say ignore this identifier all together either mkdocstring or the handlers.

**Comment by pawamoy** [comment]
Thanks for the report :slightly_smiling_face: 
We could solve this by implementing the Markdown extension as a [PyMDown Block](https://facelessuser.github.io/pymdown-extensions/extensions/blocks/) and by adding a config option to choose whether to use blocks or `:::`.

**Comment by jdpatt** [comment]
Nice, so is that just an alternative starting identifier or does it add other magic on top?  Say a few years down the road, someone is using mkdocstrings with `///` , mkdocs-click with `:::` and this new fancy one you come with by then.  Will using `/// module.to.import` just have the same problem?

Maybe its alternative syntax in `mkdocstrings` that can be optionally selected?   Make it align with how mkdocs-click did it in this instance?  Then its on each extension to collect its own signature and handle appropriately.  No idea how to enforce that and maybe this is the limitation since we have no standard around it and you can only pick one.

```rst
::: mkdocstring
    options:
        module: path.to.object
```

**Comment by pawamoy** [comment]
PyMDown Blocks are exactly designed to never clash: they all have the same syntax but use an identifier to distinguish between them. Example, if we name or block `autodoc`:

```md
/// autodoc | path.to.Class
options:
    show_root_heading: false
///
```

**Comment by jdpatt** [comment]
Nice, that is awesome!  They are experimental for now and gathering feedback, https://github.com/facelessuser/pymdown-extensions/discussions/1973.   So for mkdocstring, it will be when is it stable enough to depend on.  

I'll close this issue since this is the python handler and create a feature request around changing to the blocks in mkdocstrings proper!
