### ISSUE TITLE
Misleading return type when using `merge_init_into_class`

### ISSUE THREAD

**Issue by monosans** [mkdocstrings/python#85]
Currently, when `merge_init_into_class` and `show_signature_annotations` are enabled, the class signature looks like `None` is returned when the class is called, which looks strange and misleading:

```python
SomeClass() -> None 
``` 

The simplest solution seems to be hiding the return type for classes. The ideal solution is to take the return type from `__new__`.

**Comment by pawamoy** [comment]
I didn't even notice that, thanks. I agree that we could simply remove the return type.
