### ISSUE TITLE
Feature request - Numpy docstrings & admonitions within variable field

### ISSUE THREAD

**Issue by jonasvdd** [mkdocstrings/python#86]
First, thank you for this amazing work! 🙏🏼 

**Is your feature request related to a problem? Please describe.**
related issue:https://github.com/predict-idlab/plotly-resampler/issues/241

In the `plotly-resampler` package, we use this package to generate the mkdocs documentation for our numpy-docstrings.

Everything seems to work perfect, except for the admonitions within method variable fields. They only state the admonition highlight, but do not encapsulate the content.
As can be seen from the above issue, and the 📷 ⬇️ , this is not that visually appealing.

**Describe the solution you'd like**
I would like to have the admonitions within method variable fields, to encapsulate the admonition content.

**Describe alternatives you've considered**
I tried fiddling with the indentations / line breaks of the admonitions but nothing seems to work.

**Additional context**
![image](https://github.com/mkdocstrings/python/assets/38005924/b4dc8e2e-f90b-41eb-9daf-7685e774d284)
- [link in code](https://github.com/predict-idlab/plotly-resampler/blob/cd735c3fd2163197f3221a9dc2b0515c3852e14a/plotly_resampler/figure_resampler/figure_resampler.py#L76) from which this admonition was generated

**Comment by pawamoy** [comment]
This should be fixed by https://github.com/mkdocstrings/griffe/commit/f13fc0a7edc7c8ac14c8c482b58735a5f7301bd6. It will be released today if all goes well :slightly_smiling_face:

**Comment by jonasvdd** [comment]
Woah! Thank you for the super prompt response, Amazing work! 🔥 
Looking forward to test this! 😄
