### ISSUE TITLE
document member attributes more like parameters

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [mkdocstrings/python#95]
**Is your feature request related to a problem? Please describe.**

When trying to document the members of the setuptools_scm configuration object,
i took note, that attribtes are put out like they where methods that need more details

this is in particular frustrating as most of the members are dataclasses declared members that really could use a more compact display

**Describe the solution you'd like**

i'd love to show dataclass members and select descriptors in a more compact way

so there would be a section of the parameters that double as class attribute documentation and dataclass parameter documentation
another section for properties/descriptors with simple details (think sqlalchemy field specification, atttrs fields&co)

and then finally the detailed listing of methods that do the rest.

**Comment by pawamoy** [comment]
Griffe recently gained much better support for dataclasses, so this issue is probably fixed. Let me know if you encounter any issue with latest version of Griffe regarding dataclasses, and we will open new issues to fix them :slightly_smiling_face:
