### ISSUE TITLE
Displaying inherited fields (with dataclasses)

### ISSUE THREAD

**Issue by Peter9192** [mkdocstrings/python#97]
**Is your feature request related to a problem? Please describe.**
In our projects we often use dataclasses inheriting from one another (or pydantic basemodels, for which the issue is the same). However, I can't figure out whether it is possible to display inherited fields or their docstrings. This is annoying because (1) type information is missing or incorrect and (2) I end up with a lot of duplication in my docstrings.

**Describe the solution you'd like**
I would like the child classes to display the inherited fields as well, ideally with their docstrings.

**Describe alternatives you've considered**
see below

**Additional context**
For example with the following code 

```py
@dataclass
class Person:
    name: str
    """The person's name."""
    age: int
    """The person's age."""

class Professor(Person):
    field: str
    """The field of science."""
```

the docstring for Professor is rendered like so:
![image](https://github.com/mkdocstrings/python/assets/17080502/a9505814-ab48-47fd-ba27-66df32414ddc)

Note: the `name` and `age` attributes are not displayed. My desired behaviour is that they will be displayed.

My current "best solution" is like this:

```py
@dataclass
class Person2:
    """
    Attributes:
        name: the person's name
        age: the person's age
    """
    name: str
    age: int

@dataclass
class Professor2(Person):
    """
    Attributes:
        name: the person's name
        age: the person's age
        field: the field of science
    """
    field: str
```

which renders like so: 
![image](https://github.com/mkdocstrings/python/assets/17080502/7e4dcb7e-4621-418c-ba04-104742e60217)

Note the need for repetition and that the types are not inherited. 

Final example to demonstrate that the order is important here. If I list the childs' members first, wrong types are inserted:

```py
@dataclass
class Professor3(Person):
    """
    Attributes:
        field: the field of science
        name: the person's name
        age: the person's age
    """
    field: str
```
![image](https://github.com/mkdocstrings/python/assets/17080502/83a65b1b-e2a5-4605-a0ff-556264a9e964)

Not sure if it should be discussed separately, but I can imagine similar behaviour for inherited methods could also be useful in some circumstances.

Possibly related to #40, #58 and #95

**Comment by pawamoy** [comment]
Have you tried setting [`inherited_members: true`](https://mkdocstrings.github.io/python/usage/configuration/members/#inherited_members)?

**Comment by Peter9192** [comment]
On a side note: I just tried upgrading to the brand new griffe v0.33.0 and it broke my build with a recursion error.

**Comment by pawamoy** [comment]
The latest mkdocstrings-python does not accept Griffe 0.33. Try to upgrade mkdocstrings-python, it should downgrade Griffe at the same time, and inherited members will work :slightly_smiling_face:

**Comment by Peter9192** [comment]
Okay, that helped! Ugh, I think I had fixed it before but in the meantime messed up my versions. Sorry for the trouble. 

I guess then my only remaining request would be the same as https://github.com/mkdocstrings/python/issues/58. Thanks!
